title: Library of ShadowSlam
description: The Library of ShadowSlam
collections:
  characters:
    output: true
    permalink: /homebrew/:title
  scripts:
    output: true
    permalink: /script/:title
